#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

mkdir -p "$CADMIUMROOT/tmp"

ALPINEBRANCH=$(curl --silent https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/${ARCH_ALARM}/latest-releases.yaml | awk '/branch:/ {print}' | head -1 | cut --delimiter=" " --fields=4)
ALPINEVER=$(curl --silent https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/${ARCH_ALARM}/latest-releases.yaml | awk '/version:/ {print}' | head -1 | cut --delimiter=" " --fields=4)

ROOTFS_TAR="https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/releases/${ARCH_ALARM}/alpine-minirootfs-${ALPINEVER}-${ARCH_ALARM}.tar.gz"
if [ ! -f "$CADMIUMROOT/tmp/alpine-minirootfs-${ALPINEVER}-${ARCH_ALARM}.tar.gz" ]; then
	rm $CADMIUMROOT/tmp/alpine-minirootfs-${ALPINEVER}-${ARCH_ALARM}.tar.gz || true
	wget "$ROOTFS_TAR" -O $CADMIUMROOT/tmp/alpine-minirootfs-${ALPINEVER}-${ARCH_ALARM}.tar.gz
fi
tar xfp $CADMIUMROOT/tmp/alpine-minirootfs-${ALPINEVER}-${ARCH_ALARM}.tar.gz  -C $DESTDIR

APKLINK=$(curl --silent https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/aarch64/ | awk '/apk-tools/ {print}' | head -2 | cut --delimiter=">" --fields=2 | cut --delimiter="<" --fields=1 | sed -n 2p)
# APKLINK=$(curl --silent https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/main/${ARCH_ALARM}/ | awk '/apk-tools/ {print}' | head -1 | cut --delimiter=">" --fields=2 | cut --delimiter="<" --fields=-1)
curl -LO https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/main/${ARCH_ALARM}/${APKLINK}
tar -xzf apk-tools-static-*.apk
./sbin/apk.static -X https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/main -U --allow-untrusted -p $DESTDIR --initdb add alpine-FS_PKGS_CD_BASE

mount -o bind /dev $DESTDIR/dev
mount -t proc none $DESTDIR/proc
mount -o bind /sys $DESTDIR/sys

echo -e 'nameserver 1.1.1.1\nnameserver 1.0.0.1nnameserver 8.8.8.8\nnameserver 8.8.4.4' > $DESTDIR/etc/resolv.conf

mkdir -p $DESTDIR/etc/apk
echo "https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/main" > $DESTDIR/etc/apk/repositories
echo "https://dl-cdn.alpinelinux.org/alpine/${ALPINEBRANCH}/community" > $DESTDIR/etc/apk/repositories

$chroot $DESTDIR $qemu /sbin/apk update
# $chroot $DESTDIR $qemu /sbin/apk add networkmanager
# $chroot $DESTDIR $qemu /sbin/rc-update add NetworkManager
$chroot $DESTDIR $qemu /sbin/rc-update add devfs sysinit
$chroot $DESTDIR $qemu /sbin/rc-update add dmesg sysinit
$chroot $DESTDIR $qemu /sbin/rc-update add mdev sysinit
$chroot $DESTDIR $qemu /sbin/rc-update add hwclock boot
$chroot $DESTDIR $qemu /sbin/rc-update add modules boot
$chroot $DESTDIR $qemu /sbin/rc-update add sysctl boot
$chroot $DESTDIR $qemu /sbin/rc-update add hostname boot
$chroot $DESTDIR $qemu /sbin/rc-update add bootmisc boot
$chroot $DESTDIR $qemu /sbin/rc-update add syslog boot
$chroot $DESTDIR $qemu /sbin/rc-update add mount-ro shutdown
$chroot $DESTDIR $qemu /sbin/rc-update add killprocs shutdown
$chroot $DESTDIR $qemu /sbin/rc-update add savecache shutdown