# This is a basic workflow to help you get started with Actions
name: Build cadmium images
# Controls when the action will run. 
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-arch-arm-64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: set up environment
        run: |
          cd $GITHUB_WORKSPACE
          echo 'deb-src http://azure.archive.ubuntu.com/ubuntu/ lunar main restricted' | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt build-dep linux
          sudo apt install arch-install-scripts gcc-arm-linux-gnueabihf libarchive-tools curl wget f2fs-tools cgpt vboot-utils libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf qemu-user-static gcc-aarch64-linux-gnu debootstrap binutils-aarch64-linux-gnu git u-boot-tools binfmt-support lz4 
          
      - name: remove existing config
        run: |
          rm config
          
      - name: build arm64-arch
        run: |
          ls
          cp cadmium-configs/config-arm64-arch config
          sudo ./build-all arm64-arch.img 3G
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: arm64-arch
          path: arm64-arch.img
